thresholds:
  maxLines: 50
  maxComplexity: 10
  maxYields: 7
  maxFields: 15
  maxMethods: 20
  maxLOC: 400
  maxExports: 10
  similarityThreshold: 6
  minLines: 5
  minSimilarity: 0.6
  maxParams: 4
  maxRelatedParams: 3
  maxReasons: 3
  maxClasses: 3
  envyRatio: 2
  minClumpSize: 3
  minOccurrences: 3
  maxMagicNumbers: 5
  maxMagicStrings: 5
  maxStringGetNodes: 3
  maxUntypedVars: 3
  maxSwitches: 2
  maxCases: 5
  minLOC: 20
  minMethods: 2
  minResponsibilities: 1
  unusedMethods: 0
  unusedParameters: 0
  conditionalUsage: false
  nullChecks: 0
  maxChainLength: 3
  maxDelegationRatio: 0.5
  bidirectionalDependency: false
  sharedIntimacy: 0
  behaviorMethods: 0
  publicFields: 0
  usageRatio: 0.3
  overriddenEmpty: 0
  maxCommentDensity: 0.5
  maxAutoloads: 5
  maxGlobalVars: 20
enabledDetectors:
  - LongMethod
  - LargeClass
  - DuplicateCode
output:
  format: json
  directory: ./analysis-results
  includeDetails: true
  groupBySeverity: false
